apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: flinkappv2
build:
  local:
    concurrency: 0
  artifacts:
    - image: flinkappv2
      context: docker/flinkapp
    - image: pythonapp
      context: docker/pydata

deploy:
  helm:
    releases:
      - name: strimzi
        remoteChart: strimzi-kafka-operator
        repo: https://strimzi.io/charts/
      - name: flink-operator
        remoteChart: flink-kubernetes-operator
        repo: https://downloads.apache.org/flink/flink-kubernetes-operator-1.1.0/
      - name: myapp
        chartPath: charts/haflink
        artifactOverrides: 
          flink.image: flinkappv2
          pyapp.image: pythonapp
