apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: flinkappv2
build:
  local:
    concurrency: 0
  artifacts:
    - image: flinkappv2
      context: .
      docker:
        dockerfile: docker/Dockerfile

deploy:
  helm:
    releases:
      - name: myapp
        chartPath: myapp
        artifactOverrides: 
          flink-application.image: flinkappv2

