flink:
  jarURI: local:///vincent/workdir/flink/quickstart.jar
  upgradeMode: savepoint # stateless, savepoint !, last-state
  parallelism: 2
  image: something
  state: running # running, suspended
  savepointsStored: "\"5\""
  savepointInterval: 30m
  deploymentTimeout: 5m
pyapp:
  image: something