apiVersion: v1
kind: Secret
metadata:
  name: minio
stringData:
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "abcd1234"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio # has to match .spec.template.metadata.labels
  serviceName: "minio"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: minio # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio
      containers:
      - name: minio
        image: minio/minio
        command: ["/bin/sh","-c"]
        args: ['mkdir -p /data/flink && minio server --console-address 0.0.0.0:8080 /data']
        env:
        - name: MINIO_API_CORS_ALLOW_ORIGIN
          value: '*'
        - name: MINIO_ACCESS_KEY
          value: "test"
        - name: MINIO_SECRET_KEY
          value: "abcd1234"
        ports:
        - containerPort: 9000
          name: web
        volumeMounts:
          - mountPath: "/data"
            name: minio
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: web
  selector:
    app: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  # storageClassName: "longhorn"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
